### PR TITLE
record interruptions

### PR DESCRIPTION
**Pull request by eokoneyo**
PR for #12 

- adds code to record the number of interruptions in pomodoro session
- also only display the pause and resume button when a pomodoro session is started.

**Screenshot**

ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by LeeU1911** [comment]
Can you fix the conflict caused by me merging a restructure PR?

**Comment by eokoneyo** [comment]
@LeeU1911 fixed!

**Comment by eokoneyo** [comment]
Hey man... I'm closing this PR, its been open for a while, and it looks like you already merged in something #21   that handles this.

**Comment by LeeU1911** [comment]
@eokoneyo Thanks for your contribution. Sorry for not being responsive for a while since I didn't have enough time. I'll restructure and clean up things a bit. Then you can still contribute if interested.

Best, Vu

**Pull request closed without merging**
